### ISSUE TITLE
Should be in https://github.com/choria-plugins

### ISSUE THREAD

**Issue by jared-gs** [choria-io/provisioning-agent#98]
I think this repo would be better included in https://github.com/choria-plugins.

**Comment by ripienaar** [comment]
Perhaps but this is really badly named it’s more a whole system rather than a plugin. 

In future it will become more important we are looking to make a distribution of choria around this all nice and integrated etc

**Comment by ripienaar** [comment]
Closing this, the `agent` part is baked into the server now and we'll rename this project soon
